# Represent a Decimal Number
Convert a decimal representation of a number into an arbitrary base, with arbitrary precision (significant digits).

In [1]:
function mydigits(dec::Float64, base::Int64, prec::Int=64)
    order = log(dec)/log(base)
#    println("order=", order)
    exp = Int(floor(abs(order))*sign(order))
#    println("exp=", exp)
    d = zeros(Int,1,max(exp+1,prec))
    power = Int(exp)
    println(dec, " in base ", base, " to ", prec, " digits:")
    for i = 1:prec
#        println("i=", i, " power=",power)
        if dec/(float(base)^power) >= 1
            d[i] = floor(dec/(float(base)^power))
            dec = dec - d[i]*(float(base)^power)
        end
        power -= 1
    end
    println(d,"exp", exp)
    if dec < 1e-15
        println("exactly")
    else
        println("approx.")
    end
    println("")
end

mydigits (generic function with 2 methods)

In [25]:
mydigits(10.0,2,4)
mydigits(10.0,2,2)
mydigits(10.5,2,6)
mydigits(10.4,2,5)
mydigits(10.4,2,6)
mydigits(10.4,2,7)

10.0 in base 2 to 4 digits:
[1 0 1 0]exp3
exactly

10.0 in base 2 to 2 digits:
[1 0 0 0]exp3
approx.

10.5 in base 2 to 6 digits:
[1 0 1 0 1 0]exp3
exactly

10.4 in base 2 to 5 digits:
[1 0 1 0 0]exp3
approx.

10.4 in base 2 to 6 digits:
[1 0 1 0 0 1]exp3
approx.

10.4 in base 2 to 7 digits:
[1 0 1 0 0 1 1]exp3
approx.



In [26]:
mydigits(0.5,2,6)

0.5 in base 2 to 6 digits:
[1 0 0 0 0 0]exp-1
exactly



In [27]:
mydigits(10.0,3,4)
mydigits(11.0,3,3)
mydigits(11.0,3,4)

10.0 in base 3 to 4 digits:
[1 0 1 0]exp2
exactly

11.0 in base 3 to 3 digits:
[1 0 2]exp2
exactly

11.0 in base 3 to 4 digits:
[1 0 2 0]exp2
exactly



In [28]:
mydigits(1/3,3,1)
mydigits(1/3,3,2)
mydigits(1/9,3,3)

0.3333333333333333 in base 3 to 1 digits:
[1]exp-1
exactly

0.3333333333333333 in base 3 to 2 digits:
[1 0]exp-1
exactly

0.1111111111111111 in base 3 to 3 digits:
[1 0 0]exp-2
exactly



In [3]:
mydigits(127.0,2,8)

127.0 in base 2 to 8 digits:
[1 1 1 1 1 1 1 0]exp6
exactly

