# Generate an arbitrary linear system

In [20]:
function gen_Axb(n)
    a = rand(n)
    A = [ones(n) a]
    e = randn(Float64, n)
#    display(e)
    x = [1,2]
    b = A*x + e
    return A, x, b
end

gen_Axb (generic function with 1 method)

In [16]:
A,x,b = gen_Axb(10);
x

10-element Array{Float64,1}:
 -0.4103490912807978
 -0.8897338035662209
  0.7370710387046198
  0.267915776827846 
  0.2280311688858372
  0.4388453954332678
  0.6051349638706878
 -0.6765194039316047
 -2.0799973855453353
  1.0572506814133038

2-element Array{Int64,1}:
 1
 2

In [17]:
A

10×2 Array{Float64,2}:
 1.0  0.696225   
 1.0  0.000627002
 1.0  0.152737   
 1.0  0.963821   
 1.0  0.570939   
 1.0  0.0526269  
 1.0  0.980577   
 1.0  0.0597346  
 1.0  0.7378     
 1.0  0.940888   

In [18]:
A\b

2-element Array{Float64,1}:
 0.7137840507770996
 2.415015332761448 

In [19]:
A*x-b

10-element Array{Float64,1}:
  0.41034909128079766
  0.8897338035662209 
 -0.7370710387046198 
 -0.26791577682784595
 -0.2280311688858374 
 -0.43884539543326784
 -0.6051349638706878 
  0.6765194039316047 
  2.0799973855453353 
 -1.0572506814133038 